### PR TITLE
feat(exercises): add selfmade images to the initial exercise overview

### LINKED ISSUE #6: Mime Workout
--
As a user,
I want to have
a choice of different exercises
- [x] Create Exercises Array

### LINKED ISSUE #9: Mime Workout Card
--
As a user,
I want to view one exercise,
including
- [x] title
- [x] picture
- [x] description
- [x] length of exercise
- [x] choose MUI card

### LINKED ISSUE #10: List of Mime Workout Exercises
--
As a user,
I want to see a list of exercises
- [x] create View for List of Exercises

### PR DESCRIPTION
**Pull request by Git-Hannah**
## Motivation

Added some pictures to the MUI Cards overview of exercises to get a better idea of where it can go

## Issues closed

closes #6 
closes #9 
closes #10

### CODE REVIEW

**Comment by Git-Hannah** [comment]
Great, the images are not visible in the deployment...

**Review by doemser — APPROVED** [review]
Accidentally approved.

in your src/ions/exercises.jsx :
`image: "/../public/images/imaginary-object.png",`

these paths look wrong, since you are using a next.js Image component, you should be abled to link like this "/images/imaginary-object.png"

**Review by doemser — APPROVED** [review]
tippitytoppity! LGTM

**Comment by Git-Hannah** [comment]
Thanks, but the images are still not visible in the deployment, only on the localhost version! neither in firefox nor in chromium...

**Comment by Git-Hannah** [comment]
Ok my bad, I was watching the deployment of the main branch :D !!! Now I am happy!

**Pull request merged**
